services:
    locale.preferred_language_listener:
        class: Sokil\LocaleBundle\EventListener\PreferredLanguageListener
        arguments:
            - '@translator'
            - '%locale%'
            - '%locale.config.locales%'
            - '%locale.config.query_parameter%'
            - '%locale.config.cookie_parameter%'
            - '%locale.config.path_parameter%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: -255 }

    locale.iso_codes:
        class: Sokil\IsoCodes

    locale.iso_codes_languages:
        class: Sokil\IsoCodes
        factory: ['@locale.iso_codes', getLanguages]

    locale.supported_locales_provider:
        class: Sokil\LocaleBundle\Provider\SupportedLocalesProvider
        arguments:
            - '%locale.config.locales%'
            - '@locale.iso_codes_languages'
